Chaneg make_spin() to work with thread, and also return the output
lord63/py-spin pull request #8
Opened 2017-01-27 06:14 UTC by fruch

Subprocess can be problematic for some  applications (in case we can't pickle the function, and all the parameters)

also the outpout is very imported in most of the cases

2017-02-03 19:08 UTC, ghost requested changes

2017-02-03 19:08 UTC, xoviat commented on pyspin/spin.py
This should be:

```
if sys.version_info >= (3, 0):
    from queue import Queue
else:
    from Queue import Queue

2017-02-04 18:03 UTC, fruch commented on pyspin/spin.py
You are correct, but I like moving to futures better, see my other pull request

2017-02-12 13:45 UTC, lord63 commented
Close this PR and move the discussion to #9

2017-02-12 13:45 UTC, closed without merging